version: '3.1'

volumes:
  postgres_volume:

networks:
  postgres_net:
    driver: bridge

services:
  api:
    image: franciscofrancod/kube-news:v1
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - postgres_net
    environment:
      - DB_USERNAME=kubedevnews
      - DB_PASSWORD=Pg#123
      - DB_DATABASE=kubedevnews
      - DB_HOST=db
  db:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=kubedevnews
      - POSTGRES_PASSWORD=Pg#123
      - POSTGRES_DB=kubedevnews
    volumes:
      - postgres_volume:/data/pgdata
    ports:
      - 5432:5432
    networks:
      - postgres_net

  pgadmin:
    image: dpage/pgadmin4:6.15
    networks:
      - postgres_net
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@db.com
      PGADMIN_DEFAULT_PASSWORD: Pg#123


